### ISSUE TITLE
Race condition because of request body discarding

### ISSUE THREAD

**Issue by Inviz** [openresty/nginx-eval-module#10]
Hello! Thanks for all your work around nginx eco-system. I'm a huge fan.

I stumbled upon a race condition when deploying nginx into a dynamo in Heroku: 

Sending a POST request to location like:

    location / {
      eval {
          postgres_pass ...;
      }
      postgres_pass ...;
      set_form_input...; // or anything that reads request body 
    }

Nginx drops connection some time after sending 2nd outer request, before recieving answer from PG. Sometimes!

So I found (after 20 hours) that in cases of failure, nginx discards the body right after issuing eval request, which causes the counter to go down by 1. Then some time later, if request body is read, the socket lingers and returns empty string to outer request, causing counter to go down by 1 again, before results of 2nd PG requests have arrived. It closes connection to client and drops pq request.

![image](https://cloud.githubusercontent.com/assets/2708/21760470/605481ce-d687-11e6-9d85-4ae731717c5a.png)

What I did is commented out the lines in eval module that reset `Content-Length` and commented out `sr->discard_body = 1` . This is not perfect solution, but at least it doesn't cause the race condition. 

Any suggestions how to fix it better? I mostly debugged 1.10.2, but I think I saw it on 1.11.2 likewise (i was stupid enough to use old version)

**Comment by agentzh** [comment]
@Inviz It's wrong to use `eval` and `set_form_input_xxx` in the same location since the `eval` always runs first and it has to discard the unread request body (if any) before issuing any subrequest safely. A fix should be use the `rewrite_by_lua*` directive and `ngx.location.capture` to replace your `eval {}` directive (this is suggested in this module's README). Or even better, use the `pgmoon` library directly in `rewrite_by_lua*` without issuing any subrequests at all.

**Comment by Inviz** [comment]
@agentzh I appreciate your quick response! Again, thank you very much for your work on nginx. Openresty/nginx made me feel warm and fuzzy wherever I see chinese or russian names in logs.

Thanks for clarifying the wronghood of my doing. That makes sense. I guess I'll just stick with my hack of not discarding body for now. It doesn't seem to cause problems. My eval request does not need request body to be read, so I hope it just keeps on working.

I'm trying to build my own "version" of openresty that does not use Lua. I extended ngx_postgres & form_input to do more json stuff, and wrote my module to render mustache templates. I think I've got a pretty interesting flavor of lightweight REST with postgres.

In some sense I understand it's counter-intuitive to try to avoid Lua, because your work on OpenResty lua interface is awesome and super performant. But I wanted to go with pure C for a change, as I'm originally an interpreted-language programmer. I moved all the logic into postgres triggers and extended a bunch of ngx addons. Some highlights of my nasty hacks:

1) I made prepared statements to work in ngx_postgress
2) added json output for ngx_postgress (that handles nested json properly)
3) ngx_postgres can issue redirects on rewrite with URL interpolation
4) added `errors`  & `no_errors` ngx_postgres rewrite conditions which seek response json for `error(s)` key
5) added `form_input_json $params` command that serializes QS to json
6) wrote simple mustache template renderer that transforms json output to html

not to mention some other obscure features like composable SQL queries (a sub-request can fetch JSON from DB, which is then used to build a query)

Examples: 
https://github.com/konstruxi/skema/blob/master/conf/app/meta.conf
https://github.com/konstruxi/skema/blob/master/conf/app/resource.conf

**Comment by agentzh** [comment]
@Inviz I used to go the pure C route as you before we introduced Lua into nginx (in the year 2009). But eventually we go the Lua route. Nowadays, many Lua atop Nginx configurations run even faster or much more memory efficient than pure C/C++ nginx modules, as both our users and ourselves found out :) So don't be afraid :)

**Comment by Inviz** [comment]
Thank you! Indeed I'll try it when I get to. Thank you again for your answers, support and hard work. Cheers!
