### ISSUE TITLE
is this can used on openresty-1.13.6.1？

### ISSUE THREAD

**Issue by meyer-net** [openresty/nginx-eval-module#12]
like this：
```
location ~ /get_random_url {
        internal;
        proxy_pass http://$internal_random_url;
}

location / {
   eval $proxy_host {
      local resp = ngx.location.capture("/get_random_url", {
         method = ngx.HTTP_GET,
         args = { }
      })
      return resp.body
   }

   proxy_pass http://$proxy_host
}
```
i used eval to get the var of $proxy_host from internal url, but the $proxy_host output empty, why?

**Comment by agentzh** [comment]
@meyer-net You cannot mix eval with `ngx.location.capture`. It just does not make any sense. To assign Lua value to an nginx variable, you should use ngx_lua's `ngx.var` API instead (inside `rewrite_by_lua*` or `access_by_lua*`:

https://github.com/openresty/lua-nginx-module/#ngxvarvariable

No need to use this eval module at all.

**Comment by agentzh** [comment]
@meyer-net BTW, `eval` directive does not understand Lua. That's why I said your example does not make any sense. Seems like you abuse `eval` as `set_by_lua*`.
